### ISSUE TITLE
CytoBand appear...

### ISSUE THREAD

**Issue by bioinfomatio** [lgmgeo/AnnotSV#234] opened 2024-05-11 08:52 UTC
Hi 
(1) Why does CytoBand appear `...`?

![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/f8b661c2-46d4-4c89-a889-db58d636e429)

(2) AnnotSV-3.4,genes.ENSEMBL.sorted.bed does not contain IGK genes
Can genes.ENSEMBL.sorted.bed add IGK gene information?

![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/53024988-e83f-48d0-90b5-d45aa69ae6ef)
![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/86c23772-1b00-4b05-8662-77c4591fe213)

**Comment by lgmgeo** [comment] 2024-05-13 06:37
Hi @bioinfomatio,

> (1) Why does CytoBand appear ...?

I can't reproduce this strange `p25.3-...` cytoband annotation.
Here is the command line I used with AnnotSV 3.4.1:
`$ANNOTSV/bin/AnnotSV -SVinputFile ./test.bed -outputFile ./test.annotated.tsv -svtbedcol 4`
My test.bed input file is:
`2       50002   232650  DUP`
=> Cytoband annotation = `p25.3`

> (2) Can genes.ENSEMBL.sorted.bed add IGK gene information?

AnnotSV cannot add a specific annotation here and there.
To understand the sources of the gene annotations used, please see the "Gene annotations" section in the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf):
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/d32be998-242f-4800-b2f3-576dc6c8375a)

Best,

Véronique

**Comment by bioinfomatio** [comment] 2024-05-14 03:31
chrom	start	end	Corrected_Call	Corrected_Copy_Number
2	50001	232650000	GAIN	3

**Comment by lgmgeo** [comment] 2024-05-14 06:25
Thanks for the bug report and input coordinates.
There was indeed a bug for large SVs.
This was fixed in AnnotSV v3.4.2

**Closed** 2024-06-25 07:30 UTC
