### ISSUE TITLE
AnnotSV complains about sorting error (bedtools)

### ISSUE THREAD

**Issue by Madelinehazel** [lgmgeo/AnnotSV#34] opened 2021-01-08 18:33 UTC
Hello, 

I've encountered an issue, and I'm not sure the exact reason for it. I have an SV bed generated from an SV vcf.

The command I am using is: 
`"AnnotSV -SVinputFile all_sv.bed -SVinputInfo 1 -outputFile all_sv.bed.annotated.tsv`

I encounter an error when the file is being annotated:

`/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/bin/bedtools intersect -sorted -a ./all_sv.formatted.sorted.bed.users.sorted.bed -b /home/mcouse/AnnotSV_2.1/Annotations/SVincludedInFt/DDD/GRCh37/20190318_DDD_population_cnv.sorted.bed -wa -wb > ./all_sv.formatted.sorted.intersect.ddd
Error: Sorted input specified, but the file ./all_sv.formatted.sorted.bed.users.sorted.bed has the following out of order record
M	987	1611`

In all_sv.formatted.sorted.bed.users.sorted.bed, I see:

M	987	1603
M	987	1611

There is only one SV in the original bed that corresponds to chromosome M and start position 987 (variant M	987	1611). I suspect this may be related to the refgene annotation, as the variant intersects with RNR1:

`M	649	1603	+	RNR1	NR_137294	1603	1603	649,	1603`

Any thoughts on how this might be fixed?

Thanks for your help!

**Comment by lgmgeo** [comment] 2021-01-08 21:49
Hi,

Thanks for the bug report.
Which "AnnotSV" and "bedtools" versions did you use?

Best,
Véronique

**Comment by lgmgeo** [comment] 2021-01-08 21:50
Also, does it work if you run AnnotSV with your VCF input file (in place of the BED file)?

**Comment by lgmgeo** [comment] 2021-01-11 12:50
Dear Madeline,

I have already encountered this bug (related to the use of bedtools) with older versions of AnnotSV. But normally, from AnnotSV version 3.0 this should not happen anymore.

Can you confirm ? 
Because I can not reproduce your bug even by taking the 2 SV you provided (`M 987 1603` and `M 987 1611`)

Best,
Véronique

**Comment by Madelinehazel** [comment] 2021-01-12 14:28
Hi Veronique, 
Thank you for responding! I see, I'm using version 2.1 I will try with 3.0 and let you know if the issue persists. 
Best,
Madeline

**Comment by lgmgeo** [comment] 2021-01-27 09:28
Hi Madeline,
Any news? Can I close this issue ?

**Closed** 2021-02-11 13:17 UTC
