### ISSUE TITLE
Differing number of BED fields encountered at line: 7.  Exiting...

### ISSUE THREAD

**Issue by noorsmal** [lgmgeo/AnnotSV#55] opened 2021-08-10 11:25 UTC
I'm getting an error when using annotSv to annotate vcf previously merges using jasmine (https://github.com/mkirsche/Jasmine). 

I think the issue is caused by some variants having a 0/0 genotype in all samples (but still some supporting reads), which leaves the 5th column in the ...AnnotSV_inputSVfile.formatted.sorted.bed file blank. 

error message:

-- genesAnnotation --
bedtools intersect -sorted -a AnnotSV/20210810-132043_AnnotSV_inputSVfile.formatted.sorted.bed -b /home/MOLGEN/nsmal/promethION/AnnotSV/share/AnnotSV/Annotations_Human/Genes/GRCh38/genes.RefSeq.sorted.bed -wa -wb > AnnotSV/test-EP2702_02_8_minimap_cutesv_hg38s.tsv.tmp.tmp
Differing number of BED fields encountered at line: 7.  Exiting...

the command I used was:
$ANNOTSV/bin/AnnotSV -SVinputFile jasmine_fixvcf/sv-EP2702_02_8_minimap_cutesv_hg38s.vcf -genomeBuild GRCh38 -outputFile AnnotSV/test-EP2702_02_8_minimap_cutesv_hg38s

**Comment by lgmgeo** [comment] 2021-08-16 08:59
Hi,

Thank you for this bug report.
Can you share a Jasmine merged SV VCF? (in order to reproduce the bug)

Best regards,

Véronique

**Comment by noorsmal** [comment] 2021-08-16 09:20
[example_jasmine_vcf.txt](https://github.com/lgmgeo/AnnotSV/files/6991154/example_jasmine_vcf.txt)

**Comment by lgmgeo** [comment] 2021-08-16 12:28
I can't reproduce the bug. Which AnnotSV version did you use? And which bedtools version?

**Comment by noorsmal** [comment] 2021-08-16 12:35
AnnotSV 3.0.9
bedtools 2.15.0

**Comment by lgmgeo** [comment] 2021-08-16 12:47
The minimum bedtools version compatible with AnnotSV is version 2.25 ([README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf)).
Please, update your bedtools installation and confirm me if this fixes your bug.

**Comment by noorsmal** [comment] 2021-08-16 15:11
It works now! Sorry for the trouble.

**Comment by lgmgeo** [comment] 2021-08-16 15:39
Great!

**Closed by lgmgeo** 2021-08-16 15:39 UTC
